version: "3.8"
services:
  flask-app:
    build: ./flask-app
    image: ${DOCKER_HUB_CREDS_USR}/flask-app-mpwa:lastest
    container_name: flask-app
    ports:
    - target: 5000
      published: 5000
      protocol: tcp

  mysql:
    build: ./db
    ports:
    - target: 3306
      protocol: tcp

volumes:
   flask-app:
