version: "3.8"
services:
  flask-app:
    build: ./flask-app
    image: ${DOCKER_HUB_CREDS_USR}/flask-app-mpwa:latest
    container_name: flask-app-mpwa
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    environment: 
       DATABASE_URI: "mysql+pymysql://root:password123@mysql:3306/app-db"

  mysql:
    build: ./db
    image: mysql:5.7
    container_name: mpwa-mysql
    ports:
    - target: 3306
      protocol: tcp
    environment: 
       MYSQL_ROOT_PASSWORD: "password123"
       MYSQL_DATABASE: app-db
    volumes:
    - type: volume
      source: flask-app
      target: /var/lib/mysql

volumes:
   flask-app:
